FROM node:22.14.0-alpine AS build
WORKDIR /frontend
COPY package.json .
RUN yarn install --production
COPY public/ .
COPY src/ .
RUN yarn build

FROM nginx:stable-alpine
COPY --from=build /frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
