# @format

services:
  mongo:
    container_name: online-directory-app-mongo
    image: mongo:8.0
    restart: always
    volumes:
      - /var/db/online-directory-app:/data/db
    env_file:
      - local.env
    networks:
      - backend

  mongo-express:
    container_name: online-directory-app-mongo-express
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - 'mongo'
    env_file:
      - local.env
    networks:
      - backend

  backend:
    container_name: online-directory-app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /backend
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - 4000:4000
    depends_on:
      - 'mongo'
    env_file:
      - local.env
    networks:
      - backend

  frontend:
    container_name: online-directory-app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - 'backend'
    env_file:
      - local.env
    networks:
      - frontend

networks:
  backend: {}
  frontend: {}
