version: "3.8"

services:
    mongo:
        container_name: online-directory-app-mongo
        image: mongo:4.4
        restart: always
        volumes:
            - /var/db/online-directory-app:/data/db
        environment:
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        networks:
            - backend

    mongo-express:
        container_name: online-directory-app-mongo-express
        image: mongo-express:0.54
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_SERVER=online-directory-app-mongo
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        networks:
            - backend

    backend:
        container_name: online-directory-app-backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        working_dir: /backend
        volumes:
            - ./backend:/backend
            - /backend/node_modules
        ports:
            - 4000:4000
        networks:
            - backend

    frontend:
        container_name: online-directory-app-frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        working_dir: /frontend
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        ports:
            - 3000:80
        networks:
            - frontend

networks:
    backend: {}
    frontend: {}
