FROM node:19.9.0-alpine
WORKDIR /backend
COPY package.json .
RUN apk --no-cache --virtual build-dependencies add \
    python3 \
    make \
    g++ \
    && yarn install --production \
    && apk del build-dependencies
COPY src/ .
CMD ["yarn", "start"]
