export const LIST_CONTACTS = 'LIST_CONTACTS';
export const LIST_CONTACTS_SUCCESS = 'LIST_CONTACTS_SUCCESS';
export const LIST_CONTACTS_ERROR = 'LIST_CONTACTS_ERROR';

export const SAVE_CONTACT = 'SAVE_CONTACT';
export const SAVE_CONTACT_SUCCESS = 'SAVE_CONTACT_DONE';
export const SAVE_CONTACT_ERROR = 'SAVE_CONTACT_ERROR';

export const GET_CONTACT = 'GET_CONTACT';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const GET_CONTACT_ERROR = 'GET_CONTACT_ERROR';
